### ISSUE TITLE
How does Require throw NSException and call preconditionFailure?

### ISSUE THREAD

**Issue by kdawgwilk** [JohnSundell/Require#4]
Once you throw an `NSException` wouldn't that stop execution from continuing to the `preconditionFailure`?

**Comment by JohnSundell** [comment]
@kdawgwilk Good question! The compiler cannot guarantee that an `NSException` will stop execution, since its `raise()` method does not return `Never`. That's why `preconditionFailure` is also used, although that line will technically never get hit on Apple's platforms, only on Linux.

**Comment by kdawgwilk** [comment]
Thanks for explanation!
